# Generated by Django 4.2.20 on 2025-11-29 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='task',
            name='freeze_reason',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoppingItems', to='api.category'),
        ),
        migrations.AddField(
            model_name='task',
            name='preferred_focus_mode',
            field=models.CharField(blank=True, choices=[('pomodoro', 'Pomodoro'), ('flow', "Flow / Hero's Journey"), ('mini', 'Mini / Hop In'), ('shuffle', 'Task Shuffle'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='shopping_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.shoppingitem'),
        ),
        migrations.AlterField(
            model_name='task',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='task_voices/'),
        ),
        migrations.CreateModel(
            name='Category_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, help_text='Optional color name or hex', max_length=20)),
                ('extra_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema or sample fields for tasks in this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null = global/predefined category', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
