# Generated by Django 4.2.20 on 2025-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='key',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
