# Generated by Django 4.2.20 on 2025-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_badge_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='item_type',
            field=models.CharField(choices=[('needed', 'Needed'), ('impulsive', 'Impulsive')], default='needed', max_length=10),
        ),
    ]
