# Generated by Django 4.2.20 on 2025-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shoppingitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
