# Generated by Django 4.2.20 on 2025-12-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shoppingitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='icon',
        ),
    ]
