# Generated by Django 4.2.20 on 2025-12-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_hobby_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='schema',
        ),
        migrations.AddField(
            model_name='hobby',
            name='description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
