# Generated by Django 4.2.20 on 2025-12-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_hobby_created_at_remove_hobby_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.hobby'),
        ),
    ]
