# Generated by Django 4.2.20 on 2026-01-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reminder_notified_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='Note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
