# Generated by Django 5.1.7 on 2026-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_hobby_frozen_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='key',
            field=models.CharField(max_length=120),
        ),
    ]
